# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ayush Anand's Blog 
email: iamayushanand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi my name is Ayush and I am a competitive coder 
  my handle on most competitive websites is FanOfTourist
  I will be maintaining two projects 
  one of them is clrs in which I will post my codes on the algorithms given in the book Introduction to Algorithms 3rd edition
  this book is very recommended according to me
  second project is called Competitive Programming in which I store
  My solutions to some of the competitive programming problem
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iamayushanand.github.io" # the base hostname & protocol for your site
github_username:  iamayushanand
codeforces_username: FanOfTourist
# Build settings
markdown: kramdown
